FROM python:3.10-slim

WORKDIR /app

# Copy the chess module from within the build context
COPY chess /app/chess

# Debug: dump hash of the file into image
RUN sha256sum /app/chess/chess_utils.py

ENV PYTHONPATH="/app"

RUN echo "=== CHESS CONTENTS ===" && ls -R /app/chess
